[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = ["nodejs", "npm"]
installCmd = "pip install -r requirements.txt && cd Dashboard/frontend && npm install"
buildCmd = "cd Dashboard/frontend && npm run build"

[deploy]
startCommand = "cd Dashboard && python3 app.py"
